import type {
  ChatMessage,
  Opportunity,
  PriceRow,
  Project,
  Provider,
  ServiceOffer,
} from "@/lib/types";

export const VILLA_STAGES = [
  "التصميم والتراخيص",
  "الحفر والتسوير",
  "القواعد والميدات",
  "الهيكل والعظم",
  "المباني واللياسة",
  "التمديدات",
  "العزل",
  "التشطيبات",
  "التركيبات النهائية",
  "الأعمال الخارجية",
];

const CURRENT = 6;

export const demoProject: Project = {
  id: "demo-project",
  title: "فيلا العائلة",
  type: "villa",
  city: "الرياض",
  district: "النرجس",
  landArea: 400,
  builtArea: 280,
  floors: 2,
  currentStageNo: CURRENT,
  stages: VILLA_STAGES.map((name, i) => ({
    no: i + 1,
    name,
    state: i + 1 < CURRENT ? "done" : i + 1 === CURRENT ? "active" : "locked",
  })),
};

export const demoProviders: Provider[] = [
  {
    id: "p-abumohammed",
    businessName: "مؤسسة أبو محمد للسباكة",
    kind: "company",
    bio: "تمديدات وصيانة سباكة للفلل والعمائر. نلتزم بالمواعيد ونسلّم شغلًا نظيفًا.",
    specialties: ["سباكة"],
    tools: ["جهاز كشف تسريب", "لحام مواسير PPR", "كاميرا مجاري"],
    city: "الرياض",
    districts: ["النرجس", "الياسمين", "العارض"],
    distanceKm: 2.1,
    sla: "hour",
    workHours: "8ص–6م",
    verified: true,
    scaMembership: "20012345",
    enterpriseSize: "منشأة صغيرة",
    yearsExperience: 12,
    recommendationsCount: 34,
    commitmentPct: 96,
    phone: "0501234567",
  },
  {
    id: "p-rashid",
    businessName: "Rashid Electric — رشيد",
    kind: "resident_pro",
    bio: "فني كهرباء — تأسيس وتشطيب، خبرة في فلل شمال الرياض. أتكلم أردو وعربي.",
    specialties: ["كهرباء"],
    tools: ["فاحص جهد", "ترمومتر حراري"],
    city: "الرياض",
    districts: ["النرجس", "العارض"],
    distanceKm: 3.4,
    sla: "hour",
    workHours: "7ص–9م",
    verified: true,
    scaMembership: null,
    enterpriseSize: null,
    yearsExperience: 9,
    recommendationsCount: 21,
    commitmentPct: 93,
    phone: "0559876543",
  },
  {
    id: "p-kamal",
    businessName: "فني تكييف — كمال حسين",
    kind: "resident_pro",
    bio: "تأسيس وصيانة تكييف مركزي واسبليت.",
    specialties: ["تكييف"],
    tools: ["مضخة تفريغ", "جهاز شحن فريون"],
    city: "الرياض",
    districts: ["الياسمين"],
    distanceKm: 5.0,
    sla: "day",
    workHours: "9ص–7م",
    verified: false,
    scaMembership: null,
    enterpriseSize: null,
    yearsExperience: 4,
    recommendationsCount: 6,
    commitmentPct: null,
    phone: "0533211234",
  },
  {
    id: "p-bunyan",
    businessName: "البنيان — مورد مواد بناء",
    kind: "supplier",
    bio: "توريد مواسير وكوابل وأدوات صحية بفواتير رسمية.",
    specialties: ["توريد مواد"],
    tools: [],
    city: "الرياض",
    districts: ["النرجس", "الملقا"],
    distanceKm: 5.2,
    sla: "day",
    workHours: "8ص–10م",
    verified: true,
    scaMembership: null,
    enterpriseSize: "منشأة صغيرة",
    yearsExperience: 7,
    recommendationsCount: 9,
    commitmentPct: 91,
    phone: "0561112233",
  },
];

export const demoOpportunity: Opportunity = {
  id: "demo-opp",
  stageNo: CURRENT,
  stageName: "التمديدات",
  scope: "stage",
  budgetMin: 60000,
  budgetMax: 80000,
  note: "تمديدات كاملة سباكة وكهرباء، المخططات جاهزة.",
  state: "open",
  offers: [
    {
      id: "o1",
      providerId: "p-abumohammed",
      providerName: "مؤسسة أبو محمد للسباكة",
      recommendationsCount: 34,
      total: 28500,
      scope: "without_materials",
      durationDays: 21,
      invoiceUrl: null,
      note: "السعر بعد معاينة الموقع، شامل الاختبارات.",
      state: "submitted",
    },
    {
      id: "o2",
      providerId: "p-bunyan",
      providerName: "البنيان — مورد مواد",
      recommendationsCount: 9,
      total: 13200,
      scope: "materials_only",
      durationDays: null,
      invoiceUrl: "#فاتورة-تجريبية",
      note: "توريد كامل مواد التمديدات مع فاتورة.",
      state: "submitted",
    },
  ],
};

export const demoServiceOffers: ServiceOffer[] = [
  {
    id: "s1",
    providerName: "مؤسسة أبو محمد للسباكة",
    specialty: "سباكة",
    title: "عرض التمديدات الكاملة — خصم المرحلة",
    description: "فيلا دورين بسعر ثابت — حتى نهاية الأسبوع",
    price: 26900,
    verified: true,
  },
];

export const demoPrices: PriceRow[] = [
  { material: "حديد", unit: "طن", price: 2340, changePct: -1.2 },
  { material: "خرسانة جاهزة", unit: "م³", price: 245, changePct: 0.8 },
  { material: "مواسير PPR", unit: "حبة 4م", price: 27, changePct: -2.1 },
  { material: "كيبل 4مم", unit: "لفة", price: 410, changePct: 1.5 },
];

export const demoMessages: ChatMessage[] = [
  {
    id: "m1",
    mine: true,
    kind: "text",
    body: "السلام عليكم، أبي تسعيرة تمديدات كهرباء كاملة لفيلا دورين 400م².",
    originalLang: null,
    originalBody: null,
    createdAt: new Date(Date.now() - 3600_000).toISOString(),
  },
  {
    id: "m2",
    mine: false,
    kind: "text",
    body: "وعليكم السلام، أمرّ أعاين الموقع وبعدها أعطيك مبلغًا إجماليًا — مع المواد أو بدونها.",
    originalLang: "ur",
    originalBody: "السلام، میں سائٹ دیکھ کر کل ٹوٹل دوں گا، میٹریل کے ساتھ یا بغیر۔",
    createdAt: new Date(Date.now() - 3000_000).toISOString(),
  },
  {
    id: "m3",
    mine: true,
    kind: "guard_phone",
    body: "رقم الحارس: 0559 876 543 — اطلبه عند البوابة",
    originalLang: null,
    originalBody: null,
    createdAt: new Date(Date.now() - 1200_000).toISOString(),
  },
];
